TIDY = tidy
CHMOD = chmod
TEX = etex
PDFTEX = pdftex
XMLLINT = xmllint
XSLTPROC = xsltproc
SCP = /opt/homebrew/bin/scp


XML_RESUME = mw.resume
XML_LINT_RESUME = mw.lint.resume
TEXT_RESUME = mw.txt
UNTIDY_HTML_RESUME = mw.untidy.html
HTML_RESUME = mw.html
TEX_RESUME = mw.tex
TEX_LOG = mw.log
PDF_RESUME = mw.pdf

WEBSITE_RESUME_DEST = cyndane:/var/www/www.lanfear.net/mark/resume

RESUME_DTD = resume.dtd
TEXT_XSL = resume.txt.xsl
HTML_XSL = resume.html.xsl
TEX_XSL = resume.tex.xsl

all: $(TEXT_RESUME) $(HTML_RESUME) $(PDF_RESUME)

$(XML_LINT_RESUME): $(RESUME_DTD) $(XML_RESUME)
	$(XMLLINT) --valid --output $(XML_LINT_RESUME) --format $(XML_RESUME)

$(TEXT_RESUME): $(TEXT_XSL) $(XML_LINT_RESUME)
	$(XSLTPROC) --output $(TEXT_RESUME) $(TEXT_XSL) $(XML_LINT_RESUME)
	$(CHMOD) 644 $(TEXT_RESUME)

$(HTML_RESUME): $(UNTIDY_HTML_RESUME)
	$(TIDY) -e $(UNTIDY_HTML_RESUME)
	$(TIDY) -i $(UNTIDY_HTML_RESUME) > $(HTML_RESUME)
	$(CHMOD) 644 $(HTML_RESUME)

$(UNTIDY_HTML_RESUME): $(HTML_XSL) $(XML_LINT_RESUME)
	$(XSLTPROC) --output $(UNTIDY_HTML_RESUME) $(HTML_XSL) $(XML_LINT_RESUME)

$(TEX_RESUME): $(TEX_XSL) $(XML_LINT_RESUME)
	$(XSLTPROC) --output $(TEX_RESUME) $(TEX_XSL) $(XML_LINT_RESUME)

$(PDF_RESUME): $(TEX_RESUME)
	$(PDFTEX) $(TEX_RESUME)
	$(CHMOD) 644 $(PDF_RESUME)

resume_to_website: $(HTML_RESUME) $(PDF_RESUME)
	$(SCP) -p $(HTML_RESUME) $(WEBSITE_RESUME_DEST)
	$(SCP) -p $(PDF_RESUME) $(WEBSITE_RESUME_DEST)
	$(SCP) -p $(TEXT_RESUME) $(WEBSITE_RESUME_DEST)

clean:
	rm -f $(PDF_RESUME) $(TEXT_RESUME) $(HTML_RESUME) $(UNTIDY_HTML_RESUME) $(TEX_RESUME) $(TEX_LOG) $(XML_LINT_RESUME) # > /dev/null 2>&1
